openapi: "3.0.0"
info:
  title: "33routes API Documentation"
  description: "API for Auth, User, Route, Collection, Comment, Search, File Storage, Moderation, Bug and Report Services."
  version: "1.0.0"

paths:
  /routes:
    get:
      summary: "Получение списка маршрутов"
      description: "Возвращает список id всех доступных маршрутов."
      responses:
        200:
          description: "Список id маршрутов"
          content:
            application/json:
              schema:
                type: object
                properties:
                  routes:
                    type: array
                    items:
                      type: integer
                    description: "ID маршрута"
                example:
                  routes: [ 
                    1,
                    2,
                    3
                  ]

  /route/{route-id}:
    get:
      summary: "Просмотр информации о маршруте"
      description: "Возвращает подробную информацию о выбранном маршруте."
      parameters:
        - name: route-id
          in: path
          required: true
          schema:
            type: integer
            example: 123
      responses:
        200:
          description: "Детали маршрута"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        description: "ID юзера"
                        example: 1
                      name:
                        type: string
                        description: "ID юзера"
                        example: "Алла Иванова"
                      image_url:
                        type: string
                        description: "url аватарки"
                        example: "url"
                  route:
                    type: object
                    properties:
                      route_id:
                        type: integer
                        description: "ID маршрута"
                        example: 123
                      name:
                        type: string
                        description: "Название маршрута"
                        example: "Mountain Trail"
                      url:
                        type: string
                        description: "URL маршрута"
                        example: "url"
                      description:
                        type: string
                        description: "Описание маршрута"
                        example: "A beautiful trail in the mountains"
                      length:
                        type: integer
                        description: "Длина маршрута в метрах"
                        example: 5000
                      duration:
                        type: integer
                        description: "Продолжительность маршрута в секундах"
                        example: 7200
                      tags:
                        type: array
                        items:
                          type: string
                          enum: ["forest", "park", "near_water"]
                        description: "Теги маршрута"
                        example: ["forest", "near_water"]
                      category:
                        type: string
                        enum: ["walking"]
                        description: "Категория маршрута"
                        example: "walking"
                      created_at:
                        type: integer
                        description: "Дата создания маршрута в формате Unix"
                        example: 1616179200
                      status:
                        type: string
                        enum: ["pending", "approved", "rejected"]
                        description: "Статус маршрута"
                        example: "approved"
                      is_deleted:
                        type: boolean
                        description: "Флаг удаления маршрута"
                        example: false
                      rating:
                        type: number
                        format: float
                        description: "Средний рейтинг маршрута"
                        example: 3.5
                      images:
                        type: array
                        items:
                          type: string
                        description: "Ссылки на изображения маршрута"
                        example: ["url_to_image1", "url_to_image2"]
                  points:
                    type: array
                    description: "Точки маршрута с координатами и дополнительной информацией"
                    items:
                      type: object
                      properties:
                        point_id:
                          type: integer
                          description: "ID точки маршрута"
                          example: 1
                        coordinate:
                          type: object
                          properties:
                            latitude:
                              type: number
                              format: float
                              description: "Широта"
                              example: 45.12345
                            longitude:
                              type: number
                              format: float
                              description: "Долгота"
                              example: 12.12345
                        time_offset:
                          type: integer
                          description: "Время в секундах с начала маршрута"
                          example: 300
                        elevation:
                          type: integer
                          description: "Высота точки над уровнем моря в метрах"
                          example: 200
                        speed:
                          type: number
                          format: float
                          description: "Скорость на этой точке маршрута"
                          example: 2.5
                        point_description:
                          type: string
                          description: "Описание точки маршрута"
                          example: "Поворот у дерева"
                        images:
                          type: array
                          items:
                            type: string
                          description: "Изображения, связанные с точкой маршрута"
                          example: ["url_to_image1", "url_to_image2"]
                example:
                  user:
                    user_id: 1
                    name: "Алла Майонезова"
                    image_url: "image"
                  route:
                    route_id: 123
                    name: "Mountain Trail"
                    url: "url"
                    description: "A beautiful trail in the mountains"
                    length: 5000
                    duration: 7200
                    tags: ["forest", "near_water"]
                    category: "walking"
                    created_at: 1616179200
                    rating: 3.5
                    images: ["url_to_image1", "url_to_image2"]
                  points:
                    - point_id: 1
                      coordinate:
                        latitude: 45.12345
                        longitude: 12.12345
                      time_offset: 300
                      elevation: 200
                      speed: 2.5
                      point_description: "Поворот у дерева"
                      images: ["url_to_image1", "url_to_image2"]

  /collections:
    get:
      summary: "Получение списка подборок"
      description: "Возвращает список id всех доступных подборок."
      responses:
        200:
          description: "Список id подборок"
          content:
            application/json:
              schema:
                type: object
                properties:
                  collections:
                    type: array
                    items:
                      type: integer
                    description: "ID подборки"
                example:
                  collections: [ 
                    1,
                    2,
                    3
                  ]

  /collection/{collection-id}:
    get:
      summary: "Получение информации о подборке"
      description: "Возвращает подробную информацию о выбранной подборке."
      parameters:
        - in: path
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
      responses:
        200:
          description: "Информация о подборке"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      user_id:
                        type: integer
                        description: "ID пользователя"
                      name:
                        type: string
                        description: "Имя пользователя"
                      image_url:
                        type: string
                        description: "URL аватара пользователя"
                  collection:
                    type: object
                    properties:
                      collection_id:
                        type: int
                        description: "ID подборки"
                      name:
                        type: string
                        description: "Название подборки"
                      url:
                        type: string
                        description: "URL подборки"
                      description:
                        type: string
                        description: "Описание подборки"
                      tags:
                        type: array
                        items:
                          type: string
                          enum: ["forest", "park", "near_water"]
                        description: "Теги подборки"
                      rating:
                        type: number
                        format: float
                        description: "Средний рейтинг подборки"
                      created_at:
                        type: integer
                        description: "Дата создания подборки в формате Unix"
                      routes:
                        type: object
                        properties:
                          amount:
                            type: integer
                            description: "Количество маршрутов в подборке"
                          ids:
                            type: array
                            items:
                              type: integer
                            description: "Список id маршрутов в подборке"
                example:
                  user: 
                    user_id: 1
                    name: "Алла Майонезова"
                    image_url: "image"
                  collection: 
                    collection_id: 1 
                    name: "Best Mountain Trails" 
                    url: "url"
                    description: "adasasdassd"
                    tags: ["forest", "park"]
                    rating: 4.5
                    created_at: 1616179200
                    routes: 
                      amount: 2
                      ids: [1, 2]

  /collection:
    post:
      summary: "Создание новой подборки"
      description: "Позволяет пользователю создать новую подборку."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Название подборки"
                description:
                  type: string
                  description: "Описание подборки"
                tags:
                  type: array
                  items:
                    type: string
                    enum: ["forest", "park", "near_water"]
                  description: "Список тегов"
              example:
                name: "Favorite Trails"
                description: "Something about route"
                tags: ["forest", "park"]
      responses:
        201:
          description: "Подборка успешно создана"

    put:
      summary: "Обновление подборки"
      description: "Позволяет пользователю обновить существующую подборку. (Добавлять только измененные, то есть если name изменен, то его и добавлять в тело, а остальные - нет)"
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: header
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Название подборки"
                description:
                  type: string
                  description: "Описание подборки"
                tags:
                  type: array
                  items:
                    type: string
                    enum: ["forest", "park", "near_water"]
                  description: "Список тегов"
              example:
                description: "A beautiful trail in the mountains" 
      responses:
        200:
          description: "Подборка успешно обновлена"

    delete:
      summary: "Удаление подборки"
      description: "Позволяет пользователю удалить существующую подборку."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: header
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
      responses:
        200:
          description: "Подборка успешно удалена"

  /collection/{collection-id}/add/{route-id}:
    put:
      summary: "Добавление маршрута в подборку"
      description: "Позволяет пользователю добавить маршрут в указанную подборку."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: path
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
      responses:
        200:
          description: "Маршрут успешно добавлен в подборку"

  /collection/{collection-id}/remove/{route-id}:
    delete:
      summary: "Удаление маршрута из подборки"
      description: "Позволяет пользователю удалить маршрут из указанной подборки."
      parameters:
        - in: header
          name: session-token
          required: true
          schema:
            type: string
          description: "Токен сессии"
        - in: path
          name: collection-id
          required: true
          schema:
            type: integer
          description: "ID подборки"
        - in: path
          name: route-id
          required: true
          schema:
            type: integer
          description: "ID маршрута"
      responses:
        200:
          description: "Маршрут успешно удален из подборки"
                                                             
components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: integer
          example: 123
        username:
          type: string
          example: "johndoe"
