services:
  33routes_image_service:
    container_name: 33routes_image_service
    build:
      context: ./image_service
      dockerfile: Dockerfile
    volumes:
      - ~/33routes_images/:/home/root/33routes_images
    restart: always
    networks:
      - 33routes_backend_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.image_service.rule=PathPrefix(`/api/image`)"
      - "traefik.http.services.image_service.loadbalancer.server.port=8100"

  33routes_route_service:
    container_name: 33routes_route_service
    build:
      context: ./route_service
      dockerfile: Dockerfile
    restart: always
    networks:
      - 33routes_backend_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route_service.rule=PathPrefix(`/api/route`)"
      - "traefik.http.services.route_service.loadbalancer.server.port=8100"
    depends_on:
      33routes_postgres:
        condition: service_healthy

networks:
  33routes_backend_network:
    external: true